name: Auto-label Dependabot PRs

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened

jobs:
  label:
    if: github.actor == "dependabot[bot]"
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“ Debug PR actor (optional)
        run: echo "PR opened by: ${{ github.actor }}"

      - name: ğŸ·ï¸ Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            dependencies
            security-scan-required
